[tool.black]
line-length = 88

[tool.ruff]
actions = []

[tool.mypy]
ignore_missing_imports = true

[project]
name = "bookbuilder"
author = "Morgen Peers"
version = "0.2.0"

[project.dependencies]
pydantic = "^1.9.0"
pyyaml = "^5.4.1"
click = "^8.0.0"

[project.optional-dependencies]
dev = ["pytest", "black", "ruff", "mypy"]