"""
Taxonomy apply: interactively review proposals from system/notes/taxonomy_proposals.md
and append accepted ones to system/taxonomy.yaml.

Parses the structured proposal format written by taxonomy_evolver:
  **`parent/new_key`**
  Label: ...
  Description: ...
  Keywords: ...
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Proposal:
    parent: str
    key: str
    label: str
    description: str
    keywords: list[str]

    @property
    def full_path(self) -> str:
        return f"{self.parent}/{self.key}"


def _parse_proposals(text: str) -> list[Proposal]:
    """Extract structured proposals from the markdown output of taxonomy_evolver."""
    proposals: list[Proposal] = []

    # Match blocks starting with **`parent/key`**
    pattern = re.compile(
        r"\*\*`([^/`]+)/([^`]+)`\*\*\s*\n"
        r"Label:\s*(.+?)\s*\n"
        r"Description:\s*(.+?)\s*\n"
        r"(?:Would capture:.*?\n)?"
        r"Keywords:\s*(.+?)(?=\n\n|\n\*\*|$)",
        re.DOTALL,
    )
    for m in pattern.finditer(text):
        parent, key, label, description, kw_raw = m.groups()
        keywords = [k.strip().strip(",") for k in re.split(r"[,\s]+", kw_raw.strip()) if k.strip()]
        proposals.append(Proposal(
            parent=parent.strip(),
            key=key.strip(),
            label=label.strip(),
            description=description.strip().replace("\n", " "),
            keywords=keywords,
        ))
    return proposals


def _load_existing_keys(taxonomy_path: Path) -> set[str]:
    """Return all existing category/subcategory keys from taxonomy.yaml."""
    import yaml
    data = yaml.safe_load(taxonomy_path.read_text(encoding="utf-8")) or {}
    keys: set[str] = set()
    for cat_key, cat in data.get("categories", {}).items():
        keys.add(cat_key)
        for sub_key in (cat.get("subcategories") or {}).keys():
            keys.add(f"{cat_key}/{sub_key}")
    return keys


def _proposal_yaml_block(p: Proposal, indent: int = 6) -> str:
    """Render a proposal as a YAML subcategory block to append."""
    pad = " " * indent
    kw_str = ", ".join(p.keywords)
    lines = [
        f"{' ' * (indent - 2)}{p.key}:",
        f"{pad}label: \"{p.label}\"",
        f"{pad}description: \"{p.description}\"",
        f"{pad}keywords: [{kw_str}]",
    ]
    return "\n".join(lines)


def _find_subcategories_block_end(taxonomy_text: str, parent_key: str) -> int | None:
    """
    Find the line index just after the last subcategory entry under parent_key.
    Returns the character offset to insert new content, or None if parent not found.
    """
    lines = taxonomy_text.splitlines(keepends=True)
    in_parent = False
    in_subcategories = False
    last_subcat_end = None
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not in_parent:
            if re.match(rf"^\s{{0,2}}{re.escape(parent_key)}\s*:", line):
                in_parent = True
        elif not in_subcategories:
            if stripped == "subcategories:":
                in_subcategories = True
                last_subcat_end = sum(len(l) for l in lines[:i + 1])
        elif in_subcategories:
            # A new top-level category (0–2 spaces indent) ends the parent block
            if re.match(r"^\S|^  \S", line) and not stripped.startswith("#"):
                break
            if stripped and not stripped.startswith("#"):
                last_subcat_end = sum(len(l) for l in lines[:i + 1])
        i += 1

    return last_subcat_end


def run_taxonomy_apply(root: Path, dry_run: bool = False) -> int:
    proposals_path = root / "system" / "notes" / "taxonomy_proposals.md"
    taxonomy_path  = root / "system" / "taxonomy.yaml"

    if not proposals_path.exists():
        print("No taxonomy_proposals.md found. Run `bookbuilder agents --only taxonomy_evolver` first.")
        return 1

    text = proposals_path.read_text(encoding="utf-8")
    proposals = _parse_proposals(text)

    if not proposals:
        print("No structured proposals found in taxonomy_proposals.md.")
        print("The file may not have been generated by taxonomy_evolver, or the format changed.")
        return 1

    existing_keys = _load_existing_keys(taxonomy_path)
    taxonomy_text = taxonomy_path.read_text(encoding="utf-8")

    print(f"\nFound {len(proposals)} proposal(s) in taxonomy_proposals.md\n")

    accepted: list[Proposal] = []
    skipped_existing: list[Proposal] = []

    for p in proposals:
        if p.full_path in existing_keys or p.key in existing_keys:
            print(f"  [skip] {p.full_path} — already exists in taxonomy")
            skipped_existing.append(p)
            continue

        print(f"  Proposal: {p.full_path}")
        print(f"    Label:       {p.label}")
        print(f"    Description: {p.description}")
        print(f"    Keywords:    {', '.join(p.keywords)}")

        # Check parent exists
        if p.parent not in existing_keys:
            print(f"    [warn] parent category '{p.parent}' not found in taxonomy — will skip")
            continue

        try:
            answer = input("  Accept? [y/N] ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print("\nAborted.")
            return 1

        if answer == "y":
            accepted.append(p)
            print(f"    ✓ queued\n")
        else:
            print(f"    — skipped\n")

    if not accepted:
        print("Nothing to apply.")
        return 0

    if dry_run:
        print(f"\n[dry-run] Would apply {len(accepted)} proposal(s):")
        for p in accepted:
            print(f"  {p.full_path}")
        return 0

    # Apply accepted proposals — insert into taxonomy.yaml
    # Process in reverse order of insertion point so offsets stay valid
    insertions: list[tuple[int, str]] = []
    for p in accepted:
        offset = _find_subcategories_block_end(taxonomy_text, p.parent)
        if offset is None:
            print(f"  [error] could not find insertion point for {p.parent} — skipping {p.full_path}")
            continue
        block = "\n" + _proposal_yaml_block(p) + "\n"
        insertions.append((offset, block))

    # Apply in reverse offset order
    for offset, block in sorted(insertions, key=lambda x: -x[0]):
        taxonomy_text = taxonomy_text[:offset] + block + taxonomy_text[offset:]

    taxonomy_path.write_text(taxonomy_text, encoding="utf-8")

    print(f"Applied {len(insertions)} proposal(s) to system/taxonomy.yaml")
    print("Re-run `bookbuilder analyze --force` to reclassify items with the new categories.")
    return 0
